# Generated by Django 5.1.4 on 2025-01-09 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameraalert',
            name='captured_at',
        ),
    ]
