# Generated by Django 5.1.4 on 2025-01-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_remove_cameraalert_captured_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameraalert',
            name='camera_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cameraalert',
            name='type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
