# Generated by Django 5.1.4 on 2025-01-17 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_cameraalert_camera_id_cameraalert_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameraalert',
            name='camera_id',
        ),
        migrations.RemoveField(
            model_name='cameraalert',
            name='name',
        ),
        migrations.AddField(
            model_name='cameraalert',
            name='camera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='devices.camera'),
        ),
    ]
