# Generated by Django 5.1.4 on 2025-02-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_cameraalert_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameraalert',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='cameraalert',
            name='rule',
        ),
        migrations.AddField(
            model_name='cameraalert',
            name='camera_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='cameraalert',
            name='rule_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
