# Generated by Django 5.1.4 on 2025-02-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_remove_cameraalert_camera_remove_cameraalert_rule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameraalert',
            name='version_number',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
