# Generated by Django 5.1.4 on 2025-03-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_ruleversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.BigIntegerField(null=True)),
                ('updated_by', models.BigIntegerField(null=True)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'prompt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VLMModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.BigIntegerField(null=True)),
                ('updated_by', models.BigIntegerField(null=True)),
                ('vlmmodel_name', models.CharField(max_length=255)),
                ('vlmmodel_apikey', models.TextField()),
                ('vlmmodel_url', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'vlm_model',
                'managed': False,
            },
        ),
    ]
