# Generated by Django 5.1.4 on 2025-03-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_prompt_vlmmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameraalert',
            name='details',
            field=models.JSONField(default=None, null=True),
        ),
    ]
